sudo: required
language: node_js
node_js:
  - '8'
os: linux
branches:
  only:
  - master
script:
  - 'npm run test'
before_script:
  - 'sudo chown root /opt/google/chrome/chrome-sandbox'
  - 'sudo chmod 4755 /opt/google/chrome/chrome-sandbox'
after_success:
  - 'cat ./test/coverage/lcov.info | ./node_modules/.bin/codecov'
